name: 'Generate Release Notes'
description: 'Automatically generate changelog from commits between main branch and current branch'
author: 'Liar0320'
branding:
  icon: 'file-text'
  color: 'green'

inputs:
  compare-mode:
    required: false
    default: 'branch'
    description: 'Comparison mode: "branch" to compare against base branch, "tag" to compare between version tags (auto-detect previous tag)'
  base-branch:
    required: false
    default: 'main'
    description: 'Base branch to compare against (only used when compare-mode is "branch")'
  output-file:
    required: false
    default: ''
    description: 'Path to write complete changelog with metadata to file (e.g., RELEASE_NOTES.md). Leave empty to skip file generation'

outputs:
  changelog:
    description: 'Pure changelog content in markdown format (only commit entries)'
    value: ${{ steps.changelog.outputs.changelog }}
  release-notes:
    description: 'Complete release notes with metadata header and footer'
    value: ${{ steps.changelog.outputs.release-notes }}
  changelog-file:
    description: 'Path to the generated release notes file (if output-file is specified)'
    value: ${{ steps.changelog.outputs.changelog-file }}
  current-tag:
    description: 'Current version tag (only available when compare-mode is "tag")'
    value: ${{ steps.changelog.outputs.current-tag }}
  previous-tag:
    description: 'Previous version tag (only available when compare-mode is "tag")'
    value: ${{ steps.changelog.outputs.previous-tag }}

runs:
  using: composite
  steps:
    - name: Generate changelog from commits
      id: changelog
      shell: bash
      run: |
        ACTION_PATH="${{ github.action_path }}"
        if command -v cygpath >/dev/null 2>&1; then
          ACTION_PATH="$(cygpath -u "$ACTION_PATH")"
        fi
        "$ACTION_PATH/script.sh" "${{ inputs.compare-mode }}" "${{ inputs.base-branch }}" "${{ inputs.output-file }}"
